name: build-and-push
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  find-changed-files:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed-files.dirs }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          files: |
            base
            desktop
            laptop

  build-and-push:
    name: Build and push base image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    needs:
      if: github.event_name == 'push'
        - find-changed-files
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        image_major: ["37", "38"]
        build_variant:
          if: github.event_name == 'push'
            ${{fromJson(needs.find-out-changes.outputs.dirs)}}
          else:
            ["base", "desktop", "laptop"]
    env:
      IMAGE_NAME: custom-silverblue-${{ matrix.build_variant }}
      IMAGE_TAGS: ${{ matrix.image_major }} ${{ matrix.image_major }}-${{ github.sha }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v3

      - name: Build base image
        id: build_image
        uses: redhat-actions/buildah-build@v2.11
        with:
          containerfiles: |
            ./${{ matrix.build_variant }}/Dockerfile
          build-args: |
            IMAGE_MAJOR=${{ matrix.image_major }}
          context: ./${{ matrix.build_variant }}
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          oci: true

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase registry fix
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Push to ghcr
        uses: redhat-actions/push-to-registry@v2.7
        id: push
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
