name: build-and-push
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**/README.md"
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - "build-local.sh"

jobs:
  build-and-push-base:
    name: Build and push base image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_major: ["41"]
        image_flavour: ["silverblue", kinoite]
        build_variant: ["base"]
    env:
      IMAGE_NAME: custom-${{ matrix.image_flavour }}-${{ matrix.build_variant }}
      IMAGE_MAJOR: ${{ matrix.image_major }}
      IMAGE_FLAVOUR: ${{ matrix.image_flavour }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_MAJOR }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          build-args: |
            IMAGE_MAJOR=${{ env.IMAGE_MAJOR }}
          file: ./${{ matrix.build_variant }}/Dockerfile
          context: ./${{ matrix.build_variant }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-variant:
    name: Build and push image variants
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_major: ["41"]
        image_flavour: ["silverblue", "kinoite"]
        build_variant: ["desktop", "laptop"]
    needs: build-and-push-base
    env:
      IMAGE_NAME: custom-${{ matrix.image_flavour }}-${{ matrix.build_variant }}
      IMAGE_MAJOR: ${{ matrix.image_major }}
      IMAGE_FLAVOUR: ${{ matrix.image_flavour }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_MAJOR }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          build-args: |
            IMAGE_MAJOR=${{ env.IMAGE_MAJOR }}
          file: ./${{ matrix.build_variant }}/Dockerfile
          context: ./${{ matrix.build_variant }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
