name: build-and-push
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

env:
  IMAGE_NAME: custom-silverblue-base
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  base:
    name: Build and push base image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Build base image
        id: build_image
        uses: redhat-actions/buildah-build@v2.11
        with:
          containerfiles: |
            ./base/Dockerfile
          context: ./base
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          oci: true

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase registry fix
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Push to ghcr
        uses: redhat-actions/push-to-registry@v2.7
        id: push
        with:
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
